---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-fabric-data-product-manager-clusterrole
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]

- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["helmrepositories"]
  verbs: ["*"]

- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-fabric-data-product-manager-clusterrole
subjects:
- kind: ServiceAccount
  name: data-fabric-data-product-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: data-fabric-data-product-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io
